version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.louisdev.fr`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=leresolver"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - traefik

  api:
    build:
      context: ..
      dockerfile: prod/Dockerfile
    container_name: fastapi
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`cicd-back.louisdev.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=leresolver"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    networks:
      - traefik
      - internal

volumes:
  db_volume:

networks:
  traefik:
    external: true
  internal:
    driver: bridge
